version: 2
updates:
  - package-ecosystem: "npm"           # Use npm for managing dependencies
    directory: "/ie-bank-frontend"             # Path to where package.json is located
    schedule:
      interval: "weekly"               # Frequency of updates
