name: OSSF Scorecard
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'  # Run every Monday at 12:00 UTC

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@v2.0.0  # Use the correct version
        with:
          results_file: results.json
